// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  /* Services*/

  angular.module('app.services', []).factory('version', function() {
    return "0.1";
  });

}).call(this);

/*
//@ sourceMappingURL=services.map
*/
